apiVersion: apps/v1
kind: Deployment
metadata:
  name: ip-app-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: ip-app
  template:
    metadata:
      labels:
        app: ip-app
    spec:
      nodeSelector:
        node: worker1
      containers:
      - name: ipapp
        image: harshajain/ip-app:1
        ports:
        - containerPort: 80
